SELECT E.ID AS ID_EVENTO,
E.TITULO AS TITULO_EVENTO,
E.DESCRICAO,
E.DATA_EVENTO,
E.ACESSO_LIVRE,
TE.ID AS ID_TIPO_EVENTO,
TE.TITULO AS TITULO_TIPO_EVENTO,
I.ID AS ID_INSTITUICAO,
I.NOME_FANTASIA,
I.RAZAOSOCIAL,
I.CNPJ,
I.LOGRADOURO,
I.CEP,
I.UF,
I.CIDADE
FROM EVENTOS E 
INNER JOIN TIPOS_EVENTOS TE ON E.ID_TIPO_EVENTO = TE.ID
INNER JOIN INSTITUICOES I ON E.ID_INSTITUICAO = I.ID

SELECT * FROM TIPOS_EVENTOS
SELECT * FROM INSTITUICOES
SELECT * FROM EVENTOS
SELECT * FROM USUARIOS
SELECT * FROM CONVITES

INSERT INTO EVENTOS(TITULO, DESCRICAO, DATA_EVENTO, ACESSO_LIVRE, ID_INSTITUICAO, ID_TIPO_EVENTO)
VALUES('Perfil Vencedor', 'Aprenda técnicas para o Linkedin', '2019-04-05',1,1,2);

INSERT INTO USUARIOS(NOME, EMAIL, SENHA, TIPO_USUARIO)
VALUES('Vini', 'vini@gmail.com', '12345', 'comum'),
('Vinizaum', 'vini@gmail.com.br', '123456', 'comum')

SELECT C.ID AS ID_CONVITE
,C.SITUACAO
,E.ID AS ID_EVENTO
,E.TITULO AS TITULO_EVENTO
,E.DATA_EVENTO as DATA_EVENTO
,U.ID AS ID_USUARIO
,U.NOME AS NOME_USUARIO
,U.EMAIL AS EMAIL_USUARIO
,TE.ID AS ID_TIPO_EVENTO
,TE.TITULO AS TITULO_TIPOS_EVENTO
FROM
CONVITES C
INNER JOIN EVENTOS E
ON C.ID_EVENTO = E.ID
INNER JOIN USUARIOS U
ON C.ID_USUARIO = U.ID
INNER JOIN TIPOS_EVENTOS TE
ON E.ID_TIPO_EVENTO = TE.ID